@host =  http://localhost:5072
@id = 2
###
GET {{host}}/games/{{id}}

###
GET {{host}}/games

###
POST {{host}}/games
Content-Type: application/json

{
  "name": "Call of Duty Modern Warfare 8",
  "price": 59.99,
  "genreId": 3,
  "releaseDate": "2025-09-15"
} 

###
PUT {{host}}/games/{{id}}
Content-Type: application/json

{
  "id": {{id}},
  "name": "Call of Duty Modern Warfare 7 - Updated",
  "genreId": 2,
  "price": 49.99,
  "releaseDate": "2025-09-15"
}

###
@id=3
DELETE {{host}}/games/{{id}}