using GameStore.Api.Data;
using GameStore.Api.Endpoints;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddValidation();
var connString = "Data Source=GameStore.db";
builder.Services.AddSqlite<GameStore.Api.Data.GameStoreContext>(connString);
var app = builder.Build();
app.MapGamesEndpoints();
app.MigrateDb();
 app.Run();
